import { useState, useEffect } from 'react'
import { useParams, Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { Award, ShieldCheck, Star, Shield, CheckCircle2, XCircle, ExternalLink } from 'lucide-react'
import { useQuery } from '@tanstack/react-query'
import { appsApi } from '../services/api'
import logo from '../assets/logo.png'

export default function PublicCertificate() {
  const { certificateId } = useParams()
  
  const appId = certificateId; // The URL now directly contains the app ID for the share link

  // Fetch all apps to find the exact one
  const { data: allApps = [], isLoading } = useQuery({
    queryKey: ['public-apps-cert'],
    queryFn: () => appsApi.getAll({ limit: 1000 }).then(r => r.apps || [])
  })

  // Find the app
  const app = allApps.find(a => a.id === appId);

  // Generate Display ID
  const getCertId = (app) => {
    if (!app || allApps.length === 0) return '';
    const reversedIndex = allApps.length - allApps.findIndex(a => a.id === app.id);
    return `Loga_APP_Store_${String(reversedIndex).padStart(3, '0')}`;
  }

  const displayCertId = getCertId(app);

  if (isLoading) {
    return (
      <div className="min-h-screen bg-black flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-[#FFD700]"></div>
      </div>
    )
  }

  if (!app) {
    return (
      <div className="min-h-screen bg-[#0F1115] flex flex-col items-center justify-center p-6 text-center">
        <motion.div initial={{ scale: 0.9, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} className="bg-[#1C1C1E] p-10 rounded-3xl border border-white/10 max-w-md w-full">
          <XCircle className="w-20 h-20 text-[#FF453A] mx-auto mb-6" />
          <h1 className="text-2xl font-bold text-white mb-2">Invalid Certificate</h1>
          <p className="text-textSecondary mb-8">This certificate ID does not exist or has been revoked.</p>
          <Link to="/" className="block w-full py-3 bg-white/10 hover:bg-white/20 text-white rounded-xl font-medium transition-colors">
            Return to App Store
          </Link>
        </motion.div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-[#0F1115] py-12 px-4 md:px-8 font-['Inter',_sans-serif]">
      
      {/* Verification Banner */}
      <motion.div 
        initial={{ y: -20, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        className="max-w-[900px] mx-auto bg-[#30D158]/10 border border-[#30D158]/30 rounded-2xl p-4 flex flex-col md:flex-row items-center justify-center gap-3 text-center md:text-left mb-8"
      >
        <div className="w-10 h-10 rounded-full bg-[#30D158] flex items-center justify-center shrink-0 shadow-[0_0_20px_rgba(48,209,88,0.4)]">
          <CheckCircle2 className="w-6 h-6 text-black" />
        </div>
        <div>
          <div className="text-[#30D158] font-bold tracking-wide">CERTIFICATE VERIFIED</div>
          <div className="text-white/60 text-sm">This is an official document generated by the App Store Certification Authority.</div>
        </div>
      </motion.div>

      {/* The Certificate UI */}
      <div className="w-full max-w-full overflow-x-auto custom-scrollbar border border-white/10 rounded-2xl bg-[#0F1115] shadow-2xl">
        <div className="min-w-[1000px] p-4 md:p-8 flex justify-center">
          <motion.div 
            initial={{ scale: 0.95, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            transition={{ delay: 0.1 }}
            className="cert-container relative bg-[#0F1115] p-1 mx-auto shrink-0"
            style={{ width: '1000px', height: '707px' }}
          >
            {/* Gold Border Wrapper */}
            <div className="cert-container w-full h-full border-[4px] border-[#FFD700] rounded-2xl p-1.5 relative z-10 shadow-[0_0_20px_rgba(255,215,0,0.2)_inset,0_0_20px_rgba(255,215,0,0.2)]">
              <div className="w-full h-full border border-[#FFD700]/30 rounded-xl relative overflow-hidden bg-gradient-to-br from-[#1C1C1E] via-[#0F1115] to-[#141416] flex flex-col p-8">
            
            {/* Background decorative elements */}
            <div className="absolute top-0 right-0 w-96 h-96 bg-[#FFD700]/5 rounded-full blur-3xl -translate-y-1/2 translate-x-1/3 pointer-events-none" />
            <div className="absolute bottom-0 left-0 w-96 h-96 bg-[#0A84FF]/5 rounded-full blur-3xl translate-y-1/3 -translate-x-1/3 pointer-events-none" />
            <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] opacity-5 mix-blend-overlay pointer-events-none" />

            {/* Header */}
            <div className="flex justify-between items-start mb-4 relative z-10">
              <div className="flex items-center gap-3">
                <img src={logo} alt="Logo" className="w-12 h-12 rounded-xl border border-white/10" crossOrigin="anonymous" />
                <div>
                  <div className="text-white font-black text-xl tracking-tight">App Store</div>
                  <div className="text-[#FFD700] text-[10px] font-bold uppercase tracking-[0.2em]">Certification Authority</div>
                </div>
              </div>
              <div className="text-right hidden md:block">
                <div className="text-white/40 text-xs font-mono mb-1">CERTIFICATE ID</div>
                <div className="text-white/90 text-sm font-mono tracking-wider bg-white/5 px-3 py-1 rounded-lg border border-white/10">{displayCertId}</div>
              </div>
            </div>

            {/* Title */}
            <div className="text-center mb-4 relative z-10">
              <h1 className="text-5xl md:text-6xl font-black text-[#FFD700] tracking-tight uppercase" style={{ textShadow: '0 4px 20px rgba(255, 215, 0, 0.2)' }}>
                Official App Certificate
              </h1>
              <div className="w-24 h-1 bg-gradient-to-r from-transparent via-[#FFD700]/50 to-transparent mx-auto rounded-full" />
            </div>

            <div className="flex-1 flex flex-col items-center justify-center text-center relative z-10 max-w-3xl mx-auto w-full">
              <p className="text-xl text-white/80 italic leading-relaxed mb-4 font-serif">
                "This certificate confirms that the application has been meticulously reviewed and approved by the App Store Quality & Security Verification System."
              </p>

              <div className="bg-white/5 backdrop-blur-md border border-white/10 rounded-3xl p-6 w-full flex items-center gap-8 shadow-2xl relative overflow-hidden text-left max-w-[800px]">
                <div className="absolute inset-0 bg-gradient-to-r from-[#0A84FF]/10 to-transparent opacity-50" />
                
                <img 
                  src={app.iconUrl} 
                  alt="App Icon" 
                  className="w-32 h-32 rounded-3xl shadow-[0_0_30px_rgba(0,0,0,0.5)] border border-white/10 relative z-10 shrink-0 object-cover"
                  crossOrigin="anonymous"
                />
                
                <div className="relative z-10 flex-1 w-full flex flex-col items-start">
                  <div className="inline-block px-3 py-1 rounded-full bg-white/10 text-white/70 text-xs font-bold uppercase tracking-wider mb-2 border border-white/5">
                    {app.category}
                  </div>
                  <h2 className="text-4xl font-black text-white mb-2 leading-tight">{app.name}</h2>
                  <div className="flex items-center gap-2 text-[#0A84FF] font-medium text-lg mb-3">
                    Developed by {app.developerName || app.developer || 'Verified Developer'}
                    <ShieldCheck size={20} className="text-[#0A84FF]" style={{ display: 'inline-block', marginTop: '-2px' }} />
                  </div>
                  <p className="text-white/60 leading-relaxed text-sm" style={{ wordBreak: 'break-word' }}>
                    {(() => {
                      const desc = app.shortDescription || app.description || 'Verified and approved application for distribution.';
                      return desc.length > 130 ? desc.substring(0, 130) + '...' : desc;
                    })()}
                  </p>
                </div>
              </div>
            </div>

            <div className="mt-auto flex items-center justify-between relative z-10 border-t border-white/10 pt-4 pb-0 gap-6">
              <div className="flex justify-start gap-8">
                 <div>
                   <div className="text-[10px] text-white/40 uppercase tracking-widest font-bold mb-1">Issue Date</div>
                   <div className="text-white font-medium text-base">{new Date(app.createdAt || Date.now()).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
                 </div>
                 <div>
                   <div className="text-[10px] text-white/40 uppercase tracking-widest font-bold mb-1">Security Score</div>
                   <div className="text-[#30D158] font-bold flex items-center gap-1">100/100 <Shield size={16} className="text-[#30D158]" style={{ display: 'inline-block', marginTop: '-2px' }} /></div>
                 </div>
                 <div>
                   <div className="text-[10px] text-white/40 uppercase tracking-widest font-bold mb-1">Quality Score</div>
                   <div className="text-[#0A84FF] font-bold flex items-center gap-1">100/100 <Star size={16} fill="currentColor" className="text-[#0A84FF]" style={{ display: 'inline-block', marginTop: '-2px' }} /></div>
                 </div>
              </div>

              <div className="flex items-center gap-4">
                <div className="text-right">
                  <div className="text-white font-bold text-lg text-[#FFD700]">Verified & Approved</div>
                  <div className="text-white/40 text-xs font-mono mt-1">app.loganathanm.in</div>
                </div>
                <div className="relative w-20 h-20 flex items-center justify-center shrink-0">
                  <Award size={64} className="text-[#FFD700] absolute" style={{ opacity: 0.9 }} />
                  <div className="absolute inset-0 rounded-full border-2 border-[#FFD700] border-dashed animate-[spin_10s_linear_infinite] opacity-50" />
                  <CheckCircle2 size={24} className="text-[#141416] bg-[#FFD700] rounded-full relative z-10" />
                </div>
              </div>
            </div>

            </div>
          </div>
        </motion.div>
      </div>
    </div>

      {/* Return Button */}
      <div className="max-w-[900px] mx-auto mt-8 flex justify-center">
        <Link 
          to={`/app/${app.id}`}
          className="flex items-center gap-2 px-6 py-3 bg-white/10 hover:bg-white/20 text-white rounded-xl font-medium transition-colors border border-white/10"
        >
          View App in Store <ExternalLink className="w-4 h-4" />
        </Link>
      </div>

    </div>
  )
}
